// Mocks generated by Mockito 5.4.6 from annotations
// in livria_user/test/features/communities/application/services/community_service_utest.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:livria_user/features/communities/domain/entities/community.dart'
    as _i2;
import 'package:livria_user/features/communities/domain/entities/joined_community.dart'
    as _i3;
import 'package:livria_user/features/communities/domain/repositories/community_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommunity_0 extends _i1.SmartFake implements _i2.Community {
  _FakeCommunity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedCommunity_1 extends _i1.SmartFake
    implements _i3.JoinedCommunity {
  _FakeJoinedCommunity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CommunityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityRepository extends _i1.Mock
    implements _i4.CommunityRepository {
  MockCommunityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Community>> fetchCommunityList(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommunityList, [offset, limit]),
            returnValue: _i5.Future<List<_i2.Community>>.value(
              <_i2.Community>[],
            ),
          )
          as _i5.Future<List<_i2.Community>>);

  @override
  _i5.Future<List<_i2.Community>> getCommunitiesByUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommunitiesByUser, [userId]),
            returnValue: _i5.Future<List<_i2.Community>>.value(
              <_i2.Community>[],
            ),
          )
          as _i5.Future<List<_i2.Community>>);

  @override
  _i5.Future<List<_i2.Community>> searchCommunities(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchCommunities, [query]),
            returnValue: _i5.Future<List<_i2.Community>>.value(
              <_i2.Community>[],
            ),
          )
          as _i5.Future<List<_i2.Community>>);

  @override
  _i5.Future<_i2.Community> createCommunity({
    required String? name,
    required String? description,
    required int? type,
    required int? ownerId,
    required String? image,
    required String? banner,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCommunity, [], {
              #name: name,
              #description: description,
              #type: type,
              #ownerId: ownerId,
              #image: image,
              #banner: banner,
            }),
            returnValue: _i5.Future<_i2.Community>.value(
              _FakeCommunity_0(
                this,
                Invocation.method(#createCommunity, [], {
                  #name: name,
                  #description: description,
                  #type: type,
                  #ownerId: ownerId,
                  #image: image,
                  #banner: banner,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Community>);

  @override
  _i5.Future<_i3.JoinedCommunity> joinCommunity({
    required int? userClientId,
    required int? communityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinCommunity, [], {
              #userClientId: userClientId,
              #communityId: communityId,
            }),
            returnValue: _i5.Future<_i3.JoinedCommunity>.value(
              _FakeJoinedCommunity_1(
                this,
                Invocation.method(#joinCommunity, [], {
                  #userClientId: userClientId,
                  #communityId: communityId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.JoinedCommunity>);

  @override
  _i5.Future<void> leaveCommunity({
    required int? userClientId,
    required int? communityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveCommunity, [], {
              #userClientId: userClientId,
              #communityId: communityId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> checkUserJoined({
    required int? userId,
    required int? communityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkUserJoined, [], {
              #userId: userId,
              #communityId: communityId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
