// Mocks generated by Mockito 5.4.6 from annotations
// in livria_user/test/features/book/application/services/US12_recommendation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:livria_user/features/auth/infrastructure/datasource/auth_local_datasource.dart'
    as _i6;
import 'package:livria_user/features/book/application/services/book_service.dart'
    as _i7;
import 'package:livria_user/features/book/domain/entities/book.dart' as _i4;
import 'package:livria_user/features/book/domain/repositories/exclusion_repository.dart'
    as _i5;
import 'package:livria_user/features/book/domain/repositories/recommendation_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RecommendationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationRepository extends _i1.Mock
    implements _i2.RecommendationRepository {
  MockRecommendationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Book>> getRecommendedBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendedBooks, []),
            returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
          )
          as _i3.Future<List<_i4.Book>>);
}

/// A class which mocks [ExclusionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExclusionRepository extends _i1.Mock
    implements _i5.ExclusionRepository {
  MockExclusionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addToExclusions({
    required int? userId,
    required int? bookId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addToExclusions, [], {
              #userId: userId,
              #bookId: bookId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromExclusions({
    required int? userId,
    required int? bookId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromExclusions, [], {
              #userId: userId,
              #bookId: bookId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkIsExcluded({
    required int? userId,
    required int? bookId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkIsExcluded, [], {
              #userId: userId,
              #bookId: bookId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<int>> getExcludedBookIds({required int? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getExcludedBookIds, [], {#userId: userId}),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i6.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveAuthgData({
    required String? token,
    required int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveAuthgData, [], {
              #token: token,
              #userId: userId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<int?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<void> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setBiometricsEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBiometricsEnabled, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isBiometricsEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricsEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [BookService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookService extends _i1.Mock implements _i7.BookService {
  MockBookService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Book>> getAllBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBooks, []),
            returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
          )
          as _i3.Future<List<_i4.Book>>);

  @override
  _i3.Future<List<String>> getGenres() =>
      (super.noSuchMethod(
            Invocation.method(#getGenres, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i4.Book>> getByGenre(String? genre) =>
      (super.noSuchMethod(
            Invocation.method(#getByGenre, [genre]),
            returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
          )
          as _i3.Future<List<_i4.Book>>);

  @override
  _i3.Future<_i4.Book?> findBookById(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#findBookById, [bookId]),
            returnValue: _i3.Future<_i4.Book?>.value(),
          )
          as _i3.Future<_i4.Book?>);

  @override
  _i3.Future<List<_i4.Book>> getRandomBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomBooks, []),
            returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
          )
          as _i3.Future<List<_i4.Book>>);
}
