// Mocks generated by Mockito 5.4.6 from annotations
// in livria_user/test/features/orders/domain/repositories/US18_order_purchase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:livria_user/features/orders/domain/entities/order.dart' as _i2;
import 'package:livria_user/features/orders/domain/repositories/order_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrder_0 extends _i1.SmartFake implements _i2.Order {
  _FakeOrder_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i3.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Order> createOrder({
    required int? userClientId,
    required String? userEmail,
    required String? userPhone,
    required String? userFullName,
    required String? recipientName,
    required bool? isDelivery,
    required String? status,
    _i2.ShippingDetails? shippingDetails,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #userClientId: userClientId,
              #userEmail: userEmail,
              #userPhone: userPhone,
              #userFullName: userFullName,
              #recipientName: recipientName,
              #isDelivery: isDelivery,
              #status: status,
              #shippingDetails: shippingDetails,
            }),
            returnValue: _i4.Future<_i2.Order>.value(
              _FakeOrder_0(
                this,
                Invocation.method(#createOrder, [], {
                  #userClientId: userClientId,
                  #userEmail: userEmail,
                  #userPhone: userPhone,
                  #userFullName: userFullName,
                  #recipientName: recipientName,
                  #isDelivery: isDelivery,
                  #status: status,
                  #shippingDetails: shippingDetails,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Order>);

  @override
  _i4.Future<List<_i2.Order>> getOrdersByUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersByUser, [userId]),
            returnValue: _i4.Future<List<_i2.Order>>.value(<_i2.Order>[]),
          )
          as _i4.Future<List<_i2.Order>>);
}
