// Mocks generated by Mockito 5.4.6 from annotations
// in livria_user/test/features/communities/domain/repositories/post_repository_impl_utest.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:livria_user/features/communities/domain/entities/post.dart'
    as _i5;
import 'package:livria_user/features/communities/infrastructure/datasource/post_remote_datasource.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteDataSource extends _i1.Mock
    implements _i3.PostRemoteDataSource {
  MockPostRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Post>> fetchPostsByCommunityId(
    int? communityId,
    int? offset,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPostsByCommunityId, [
              communityId,
              offset,
              limit,
            ]),
            returnValue: _i4.Future<List<_i5.Post>>.value(<_i5.Post>[]),
          )
          as _i4.Future<List<_i5.Post>>);

  @override
  _i4.Future<_i2.Response> fetchPostById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPostById, [id]),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#fetchPostById, [id])),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> createPost({
    required int? communityId,
    required int? userId,
    required String? username,
    required String? content,
    String? img,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #communityId: communityId,
              #username: username,
              #content: content,
              #img: img,
            }),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#createPost, [], {
                  #communityId: communityId,
                  #username: username,
                  #content: content,
                  #img: img,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);
}
